apiVersion: apps/v1
kind: Deployment
metadata:
  name: pankaj-nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: pankajhunja
        image: pankajhunja/pankaj-nginx:1.0
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred

